version = 1
SPDX-PackageName = "GammaRay"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDAB/GammaRay"

#misc source code
[[annotations]]
path = ["**.ui", "**.qrc", "**.qrc.in", "**.json", "CMakePresets.json", "GammaRay.desktop", "app/Info.plist.in", "client/Info.plist.in", "launcher/app/Info.plist.in", "launcher/cli/Info.plist.in", "com.kdab.GammaRay.metainfo.xml", "resources/gammaray/authors", "docs/collection/about.txt", "**.frag", "**.geom", "**.vert", "**.ts", "**.qm", "**.map", "cmake/gammaray.rc.cmake"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-2.0-or-later"

#misc documentation
[[annotations]]
path = ["CHANGES", "CONTRIBUTORS.txt", "INSTALL.md", "README.md", "docs/manual/style/**", "ui/resources/gammaray/ui/icons/classes/**/**", "docs/api/**.dox", "docs/api/**.html", "docs/man/**.pod", "docs/**.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-2.0-or-later"

#misc config files
[[annotations]]
path = ["version.txt", "3rdparty/**/qt_attribution.json", ".clang-format", ".clang-tidy", ".clangd", ".clazy", ".cmake-format.py", ".codespellrc", ".emacs-dirvars", ".git-blame-ignore-revs", ".gitattributes", ".gitignore", ".kateconfig", ".krazy", ".mdlrc", ".mdlrc.rb", ".pep8", ".pre-commit-config.yaml", ".pylintrc", ".qmake.conf", ".editorconfig", ".shellcheckrc", ".tag", "distro/**", "format.config.uncrustify.4_spaces", "**.qdocconf", "format_sources", "docs/collection/gammaray.qhcp.cmake", "examples/yocto/gammaray_git**.bb", "probe/gammaray_probe-android-dependencies.xml", "docs/api/Doxyfile.cmake", ".github/**", "REUSE.toml", "3rdparty/.clang-format"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

#artwork
[[annotations]]
path = ["ui/resources/gammaray/**.png", "plugins/guisupport/images/**.png", "ui/resources/gammaray/ui/icons/classes/**/**.png", "ui/resources/gammaray/ui/**/**/**.png", "docs/manual/**/**.png", "docs/api/**.png", "tests/manual/**.png", "plugins/positioning/**.png", "plugins/quickinspector/textureextension/resources/**.png", "launcher/ui/resources/launcher/**.png", "ui/resources/svg/**.svg", "ui/resources/svg/**.svgz", "plugins/positioning/direction_marker.svg", "ui/resources/gammaray/GammaRay.icns", "ui/resources/gammaray/GammaRay.ico"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-2.0-or-later"

# 3rdparty Qt subtree and resourcemodel have been removed in minimal client-only tree

[[annotations]]
path = ["launcher/ui/processlist.h", "launcher/ui/processlist_unix.cpp", "launcher/ui/processlist_win.cpp"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011 Nokia Corporation and/or its subsidiary(-ies)"
SPDX-License-Identifier = "LGPL-2.1-only OR LicenseRef-Qt-LGPL-EXCEPTION"

## StackWalker removed in minimal client-only tree

#3rdparty lz4
[[annotations]]
path = "3rdparty/lz4/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2020, Yann Collet"
SPDX-License-Identifier = "BSD-2-Clause"

## backward-cpp removed in minimal client-only tree

#3rdparty from KDE
[[annotations]]
path = ["cmake/ECM/modules/**", "cmake/ECM/find-modules/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "3rdparty/kde/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "LGPL-2.0-or-later"

## kuserfeedback removed/disabled in minimal client-only tree

# doxygen awesome
[[annotations]]
path = "docs/api/doxygen-awesome.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2023 jothepro"
SPDX-License-Identifier = "MIT"
